### ISSUE TITLE
DIR-846

### ISSUE THREAD

**Issue by whitepoet** [Tyaoo/IoT-Vuls#1]
想问下师傅DIR-846是仿真的嘛，如果是仿真用的是哪个仿真的？

**Comment by Tyaoo** [comment]
是的，好像用的FirmAE

**Comment by Tyaoo** [comment]
> 想问下师傅DIR-846是仿真的嘛，如果是仿真用的是哪个仿真的？

是的，好像用的FirmAE

**Comment by whitepoet** [comment]
但是我用firmAE web访问不上去，就是一直跳转到index.html然后这个页面是空白的

**Comment by Tyaoo** [comment]
> 但是我用firmAE web访问不上去，就是一直跳转到index.html然后这个页面是空白的

我忘了当时有没有进行过一些定制化的处理

**Comment by whitepoet** [comment]
好的，感谢~
